import type { Metadata } from "next";
import { literata, satoshi, satoshiVariable } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${literata.variable} ${satoshi.variable} ${satoshiVariable.variable} bg-background font-satoshi antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
