import type { Metadata } from "next";
import {
  britney,
  britneyVariable,
  newTitle,
  newTitleVariable,
  melodrama,
  melodramaVariable,
} from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${britney.variable} ${britneyVariable.variable} ${newTitle.variable} ${newTitleVariable.variable} ${melodrama.variable} ${melodramaVariable.variable} bg-background antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
